services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traffic-backend
    ports:
      - "8000:8000"
    volumes:
      - model-data:/app/saved_model

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: traffic-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  model-data:
